FROM php:8.5-fpm-alpine

RUN apk add --no-cache \
        icu-dev \
        sqlite \
        sqlite-dev \
        oniguruma-dev \
        libzip-dev \
        nginx \
        supervisor \
        $PHPIZE_DEPS

RUN docker-php-ext-install \
        pdo \
        pdo_sqlite \
        intl \
        mbstring \
        zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY composer.json composer.lock ./
RUN composer install --no-dev --prefer-dist --no-progress --no-interaction

COPY . .

RUN mkdir -p /run/nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY supervisord.conf /etc/supervisord.conf
COPY docker/init-perms.sh /usr/local/bin/init-perms.sh

RUN chmod +x /usr/local/bin/init-perms.sh

EXPOSE 8080

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
